name: Backend API Automation for Restful Booker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: 30 1 * * * # Runs daily at 7 AM IST

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    strategy:
      matrix:
        env: [STAGE, PROD]   # 🔁 Two environments

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Execute Tests on ${{ matrix.env }}
      run: mvn clean test -Dsuite=suite -Denv=${{ matrix.env }} -X

    - name: Upload Logs (${{ matrix.env }})
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Logs-${{ matrix.env }}
        path: logs/

    - name: Upload Test HTML Report as Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
         name: Test Report
         path: report.html     

    - name: Publish Test Report (${{ matrix.env }})
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results - ${{ matrix.env }}
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit
